import pathlib
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[2]


class WindowsInstallerBuilderTests(unittest.TestCase):
    def test_windows_builder_targets_next_repo_assets(self):
        content = (ROOT / "packaging" / "windows" / "build-setup.ps1").read_text(encoding="utf-8")
        self.assertIn("local-ai-control-center", content)
        self.assertIn("Local AI Control Center", content)
        self.assertIn("Local-AI-Control-Center-Setup", content)

    def test_windows_inno_setup_mentions_unified_installer_choices(self):
        content = (ROOT / "packaging" / "windows" / "LocalAIControlCenterSetup.iss").read_text(encoding="utf-8")
        self.assertIn("Access mode", content)
        self.assertIn("TurboQuant", content)
        self.assertIn("OpenCode", content)
        self.assertIn("Unified", content)
        self.assertIn("Guided model selection", content)
        self.assertIn("Prikazi jos modela", content)
        self.assertIn("GetWizardFallbackDefaultModelId", content)
        self.assertIn("authoritative shared catalog is read later by install.ps1", content)
        self.assertNotIn("default follows defaultModelId from the shared catalog", content)
        self.assertIn("gemma-4-e4b-it-q4-0", content)
        self.assertIn("install-summary.txt", content)
        self.assertIn("support\\launcher\\windows", content)
        self.assertIn("function GetModelField(ModelIndex: Integer; FieldName: string): string;", content)
        self.assertIn("function GetSelectedModelIndex(): Integer;", content)
        self.assertIn("function GetWorkspaceRoot(): string;", content)
        self.assertIn("GetEnv('USERPROFILE')", content)
        self.assertIn("for modelIndex := 0 to GetModelOptionCount() - 1 do", content)
        self.assertNotIn("{userprofile}", content)
        self.assertNotIn("ModelSelectionPage.Values[1]", content)
        self.assertNotIn("ModelSelectionPage.Values[2]", content)
        self.assertEqual(content.count("FieldName = 'option'"), 3)

    def test_windows_installer_script_invokes_legacy_core_install(self):
        content = (ROOT / "install" / "windows" / "install.ps1").read_text(encoding="utf-8")
        self.assertIn("legacy", content.lower())
        self.assertIn('$InstallRoot = "$env:USERPROFILE\\LocalAIControlCenter"', content)
        self.assertIn('Join-Path $env:USERPROFILE "LocalAIControlCenter"', content)
        self.assertIn("control-center-next", content)
        self.assertIn("Start-LegacyRuntimeIfNeeded", content)
        self.assertIn("selectedModelId", content)
        self.assertIn("selectedModelDownloadFile", content)
        self.assertIn("defaultModelId", content)
        self.assertIn("Get-RecommendedModelCatalog", content)
        self.assertIn("recommended-models.json", content)
        self.assertIn("catalog-default", content)
        self.assertIn("Write-InstallSummary", content)
        self.assertIn("support\\launcher\\windows", content)
        self.assertIn('$assetsDir = Join-Path $workspaceRoot "assets\\icons"', content)
        self.assertIn("function Get-WorkspaceSeedSource", content)
        self.assertIn('Copy-FolderContent -Source (Get-WorkspaceSeedSource -PrimaryRelativePath "support\\config\\profiles" -FallbackRelativePath "config\\profiles") -Destination (Join-Path $workspaceRoot "config\\profiles")', content)
        self.assertIn('Copy-FolderContent -Source (Get-WorkspaceSeedSource -PrimaryRelativePath "support\\scripts" -FallbackRelativePath "scripts") -Destination (Join-Path $workspaceRoot "scripts")', content)
        self.assertIn('Copy-FolderContent -Source (Get-WorkspaceSeedSource -PrimaryRelativePath "support\\assets\\icons" -FallbackRelativePath "assets\\icons") -Destination (Join-Path $workspaceRoot "assets\\icons")', content)
        self.assertIn("install.log", content)
        self.assertIn("Next step:", content)
        self.assertIn("function Find-ExistingExecutablePath", content)
        self.assertIn('Join-Path $env:LOCALAPPDATA "Programs\\Python\\Python312\\python.exe"', content)
        self.assertIn('Join-Path $env:LOCALAPPDATA "Microsoft\\WinGet\\Packages"', content)
        self.assertIn('Get-ChildItem -Path $packagesRoot -Directory -Filter "OpenJS.NodeJS.LTS_*"', content)
        self.assertIn("$resolvedLabel = [string]$catalogEntry.label", content)
        self.assertIn("$resolvedDownloadFile = [string]$catalogEntry.downloadFile", content)
        self.assertIn('customSource = if ($catalogEntry -and $catalogEntry.customSource)', content)
        self.assertIn('repo = if ($catalogEntry -and $catalogEntry.repo)', content)
        self.assertIn("function Register-InstallerSelectedModelWithLegacyCatalog", content)
        self.assertIn("function Sync-BootstrappedModelIntoWorkspace", content)
        self.assertIn("function Normalize-WorkspaceBranding", content)
        self.assertIn("Add-UnslothCustomModel -Repo $repo -FileName $downloadFile", content)
        self.assertIn('$modelIdToDownload = [string]$SelectedModelSelection.legacyModelId', content)
        self.assertIn('-ModelId $modelIdToDownload -Download', content)
        self.assertIn("Sync-BootstrappedModelIntoWorkspace -SelectedModelSelection $SelectedModelSelection", content)
        self.assertIn("local-ai-control-center-common.ps1", content)
        self.assertNotIn("local-qwen-common.ps1", content)
        self.assertIn('Join-Path $npmDir "node_modules\\opencode-ai\\bin\\opencode.exe"', content)
        self.assertIn('Join-Path $installRoot "apps\\llama.cpp\\bin\\llama-server.exe"', content)
        self.assertIn('joes021/local-ai-control-center', content)
        self.assertIn("[string]$IconPath = \"\"", content)
        self.assertIn('$shortcut.IconLocation = "$IconPath,0"', content)
        self.assertIn("function Write-DesktopFolderMetadata", content)
        self.assertIn("IconResource=$IconPath,0", content)
        self.assertIn("attrib +h +s $desktopIniPath", content)
        self.assertIn("attrib +r $FolderPath", content)
        self.assertIn('$controlCenterIconPath = Join-Path $assetsDir "control-center.ico"', content)
        self.assertIn('$openCodeIconPath = Join-Path $assetsDir "opencode-control-center.ico"', content)
        self.assertIn('Write-Shortcut -ShortcutPath (Join-Path $desktopDir "Local AI Control Center.lnk") -TargetPath $launchWrapper -IconPath $controlCenterIconPath', content)
        self.assertIn('Write-Shortcut -ShortcutPath (Join-Path $desktopDir "OpenCode - Local AI Control Center.lnk") -TargetPath (Resolve-OpenCodePath) -IconPath $openCodeIconPath', content)
        self.assertIn("Write-DesktopFolderMetadata -FolderPath $desktopDir -IconPath $controlCenterIconPath", content)
        catalog_block = content.split("if ($catalogEntry) {", 1)[1].split("if ([string]::IsNullOrWhiteSpace($resolvedLabel)) {", 1)[0]
        self.assertIn("$resolvedLabel = [string]$catalogEntry.label", catalog_block)
        self.assertIn("$resolvedDownloadFile = [string]$catalogEntry.downloadFile", catalog_block)
        self.assertIn("$resolvedVramClass = [string]$catalogEntry.vramClass.label", catalog_block)
        self.assertNotIn("IsNullOrWhiteSpace($resolvedLabel)", catalog_block)
        self.assertNotIn("IsNullOrWhiteSpace($resolvedDownloadFile)", catalog_block)

    def test_windows_installer_uses_catalog_as_authoritative_metadata_source(self):
        content = (ROOT / "install" / "windows" / "install.ps1").read_text(encoding="utf-8")
        self.assertIn("$selectionSource = \"wizard\"", content)
        self.assertIn("$selectionSource = \"catalog-default\"", content)
        self.assertIn("$selectionSource = \"catalog-fallback\"", content)
        self.assertIn("$catalogEntry = $catalog.recommended | Where-Object { $_.modelId -eq $resolvedModelId }", content)
        self.assertIn("if (-not $catalogEntry -and $resolvedModelId -ne $catalogDefaultModelId) {", content)
        self.assertIn("if ([string]::IsNullOrWhiteSpace($resolvedLabel)) {", content)
        self.assertIn("if ([string]::IsNullOrWhiteSpace($resolvedDownloadFile)) {", content)
        self.assertIn("if ([string]::IsNullOrWhiteSpace($resolvedVramClass)) {", content)

    def test_windows_launcher_honors_access_mode_and_force_restart(self):
        content = (ROOT / "launchers" / "windows" / "start-control-center-next.ps1").read_text(encoding="utf-8")
        self.assertIn("Get-RequestedAccessMode", content)
        self.assertIn("Get-RequestedHost", content)
        self.assertIn("CONTROL_CENTER_NEXT_FORCE_RESTART", content)
        self.assertIn("runtime-config.json", content)
        self.assertIn('Join-Path $env:USERPROFILE "LocalAIControlCenter"', content)
        self.assertNotIn('Join-Path $env:USERPROFILE "LocalQwenHome"', content)
        self.assertIn('LocalAIControlCenterNextStartup', content)

    def test_windows_inno_setup_uses_local_ai_control_center_workspace_name(self):
        content = (ROOT / "packaging" / "windows" / "LocalAIControlCenterSetup.iss").read_text(encoding="utf-8")
        self.assertIn("LocalAIControlCenter", content)
        self.assertNotIn("LocalQwenHome", content)


if __name__ == "__main__":
    unittest.main()
